/* Allegro datafile object indexes, produced by grabber v4.2.0 (beta4), MinGW32 */
/* Datafile: d:\Desenvolvimento\Construindo Palavras\PalavrasUnificado1.1.0.5\Imagens.dat */
/* Date: Tue Jan 03 19:49:26 2006 */
/* Do not hand edit! */

#define Balao1                           0        /* BMP  */
#define Balao2                           1        /* BMP  */
#define Balao3                           2        /* BMP  */
#define Bola                             3        /* BMP  */
#define Continue                         4        /* BMP  */
#define Creditos                         5        /* BMP  */
#define Desce                            6        /* BMP  */
#define DicaMenu                         7        /* BMP  */
#define F0                               8        /* BMP  */
#define F1                               9        /* BMP  */
#define F2                               10       /* BMP  */
#define F3                               11       /* BMP  */
#define F4                               12       /* BMP  */
#define F5                               13       /* BMP  */
#define F6                               14       /* BMP  */
#define Fim                              15       /* BMP  */
#define Final                            16       /* BMP  */
#define Instrucoes                       17       /* BMP  */
#define InstrucoesCanto                  18       /* BMP  */
#define LA                               19       /* BMP  */
#define LA1                              20       /* BMP  */
#define LA2                              21       /* BMP  */
#define LA3                              22       /* BMP  */
#define LB                               23       /* BMP  */
#define LC                               24       /* BMP  */
#define LC1                              25       /* BMP  */
#define LD                               26       /* BMP  */
#define LE                               27       /* BMP  */
#define LE1                              28       /* BMP  */
#define LE2                              29       /* BMP  */
#define LF                               30       /* BMP  */
#define LG                               31       /* BMP  */
#define LH                               32       /* BMP  */
#define LI                               33       /* BMP  */
#define LI1                              34       /* BMP  */
#define LJ                               35       /* BMP  */
#define LK                               36       /* BMP  */
#define LL                               37       /* BMP  */
#define LM                               38       /* BMP  */
#define LN                               39       /* BMP  */
#define LO                               40       /* BMP  */
#define LO1                              41       /* BMP  */
#define LO2                              42       /* BMP  */
#define LO3                              43       /* BMP  */
#define LP                               44       /* BMP  */
#define LQ                               45       /* BMP  */
#define LR                               46       /* BMP  */
#define LS                               47       /* BMP  */
#define LT                               48       /* BMP  */
#define LU                               49       /* BMP  */
#define LU1                              50       /* BMP  */
#define LU2                              51       /* BMP  */
#define LV                               52       /* BMP  */
#define LW                               53       /* BMP  */
#define LX                               54       /* BMP  */
#define LY                               55       /* BMP  */
#define LZ                               56       /* BMP  */
#define Ness0D1                          57       /* BMP  */
#define Ness0L1                          58       /* BMP  */
#define Ness0R1                          59       /* BMP  */
#define Ness0U1                          60       /* BMP  */
#define Ness1D1                          61       /* BMP  */
#define Ness1D2                          62       /* BMP  */
#define Ness1L1                          63       /* BMP  */
#define Ness1L2                          64       /* BMP  */
#define Ness1R1                          65       /* BMP  */
#define Ness1R2                          66       /* BMP  */
#define Ness1U1                          67       /* BMP  */
#define Ness1U2                          68       /* BMP  */
#define Ness2D1                          69       /* BMP  */
#define Ness3D1                          70       /* BMP  */
#define Niveis                           71       /* BMP  */
#define Nuvens1                          72       /* BMP  */
#define Nuvens2                          73       /* BMP  */
#define Nuvens3                          74       /* BMP  */
#define Opcoes                           75       /* BMP  */
#define Parabens                         76       /* BMP  */
#define Quadro                           77       /* BMP  */
#define Sobe                             78       /* BMP  */
#define Titulo                           79       /* BMP  */
#define Topo                             80       /* BMP  */
#define ZZZ                              81       /* BMP  */

